---
- hosts: all
  user: vagrant
  sudo: yes
  tasks:

    - name: install epel
      action: command creates=/etc/yum.repos.d/epel.repo rpm -Uvh http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm

    - name: make sure packages are installed
      action: yum pkg={{item}} state=installed
      with_items:
        - vim
        - gcc-gfortran
        - jasper
        - jasper-devel
        - libpng-devel

    - name: set NetCDF environment variable
      lineinfile: dest=/etc/environment line="NETCDF=/usr/local"

    - name: set FC environment variable
      lineinfile: dest=/etc/environment line="FC=gfortran"
    - name: set F77 environment variable
      lineinfile: dest=/etc/environment line="F77=gfortran"

    - name: Download NetCDF
      command: creates=~/netcdf-4.3.3.1.tar.gz chdir=~/ wget -T 40  ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.3.3.1.tar.gz

    - name: untar NetCDF
      command: creates=~/netcdf-4.3.3.1 chdir=~/ tar zxf netcdf-4.3.3.1.tar.gz

    - name: configure NetCDF
      command: creates=~/netcdf-4.3.3.1/Makefile chdir=~/netcdf-4.3.3.1/ ./configure  --disable-dap --disable-netcdf-4 --enable-shared=no

    - name: install NetCDF
      command: creates=/usr/local/lib/libnetcdf.a chdir=~/netcdf-4.3.3.1/ make install

    - name: Download NetCDF Fortran
      command: creates=~/netcdf-fortran-4.4.2.tar.gz chdir=~/ wget -T 40  ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.2.tar.gz

    - name: untar NetCDF Fortran
      command: creates=~/netcdf-fortran-4.4.2 chdir=~/ tar zxf netcdf-fortran-4.4.2.tar.gz 

    - name: configure NetCDF fortran
      command: creates=~/netcdf-fortran-4.4.2/Makefile chdir=~/netcdf-fortran-4.4.2/ ./configure  --enable-shared=no

    - name: install NetCDF Fortran
      command: creates=/usr/local/lib/libnetcdff.a  chdir=~/netcdf-fortran-4.4.2/ make install

    - name: Download WRF
      command: creates=~/WRFV3.7.1.TAR.gz chdir=~/ wget -T 40  http://www2.mmm.ucar.edu/wrf/src/WRFV3.7.1.TAR.gz

    - name: untar WRF
      command: creates=~/WRFV3 chdir=~/ tar zxf WRFV3.7.1.TAR.gz

    - name: Download WPS
      command: creates=~/WPSV3.7.1.TAR.gz chdir=~/ wget -T 40  http://www2.mmm.ucar.edu/wrf/src/WPSV3.7.1.TAR.gz

    - name: Download WPS Data 30KM
      command: creates=~/wps_30km.tar.gz chdir=~/ wget -T 40  http://www2.mmm.ucar.edu/wrf/src/data/wps_30km.tar.gz

    - name: Download WPS Data 4 Jan 
      command: creates=~/real4jan00.tar.gz chdir=~/ wget -T 40  http://www2.mmm.ucar.edu/wrf/src/data/real4jan00.tar.gz

    - name: set JASPER environment variable
      lineinfile: dest=/etc/environment line="JASPERLIB=/usr/lib/"

    - name: set JASPER environment variable
      lineinfile: dest=/etc/environment line="JASPERINC=/usr/include/"

# for pv (from helper script):
# rpm -i http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm 
# 
